#!/bin/sh

# Gets the invidious instance from environment vars.
INVIDIOUS_INSTANCE=$(printenv INVIDIOUS_INSTANCE)
MPV_ARGUMENTS=$(printenv MPV_ARGUMENTS)
SEARCH_TERM=""

# If INVIDIOUS_INSTANCE is empty then make a default one.
if [ -z "$INVIDIOUS_INSTANCE" ]; then
	INVIDIOUS_INSTANCE="https://invidious.sevengames.xyz"
fi

if [ -z "$MPV_ARGUMENTS" ]; then
	MPV_ARGUMENTS="--no-terminal"
fi

# If the argument is search then take every argument after that and -
# add it to SEARCH_TERM.
if [ "$1" = "-s" ] || [ "$1" = "--search" ]; then
	for thing in "$@"; do
		[ "${thing}" = "-s" ] || [ "${thing}" = "--search" ] && continue
		SEARCH_TERM=${SEARCH_TERM}${thing}" "
	done
	
	SEARCH_TERM=${SEARCH_TERM%?}
fi

# Prints the help screen then exits the program.
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
	printf "yt by 7Games (Benjamin) \
		\nusage: yt [-h, -i, -s [search]] \
		\n\n -i, --id\t gets the video by its video id \
		\n -s, --search\t takes in string and uses it to search with ytsearch \
		\n -h, --help\t displays this help and exit \
		\n\nMore info: man 1 yt"
	exit
fi

# If the argument is id then take the argument and play it in MPV.
if [ "$1" = "-i" ] || [ "$1" = "--id" ]; then
	mpv $MPV_ARGUMENTS "$INVIDIOUS_INSTANCE/watch?v=$2"
else
	# If SEARCH_TERM is empty then take user input.
	if [ "$SEARCH_TERM" = "" ]; then
		printf "Enter a search term: "
		read -r SEARCH_TERM
	fi

	# Run ytsearch with the search term and interact argument, take the output -
	# using tee and put it at /tmp/yttmp.
	INVIDIOUS_INSTANCE=$INVIDIOUS_INSTANCE ytsearch -i "$SEARCH_TERM" | tee /tmp/yttmp
	
	# Run MPV with its arguments and get the last line in /tmp/yttmp -
	# (the video url) and play it.
	mpv $MPV_ARGUMENTS "$(tail -1 /tmp/yttmp)"
	
	# Removes the temp file.
	rm /tmp/yttmp
fi

