#!/bin/sh

# Gets the invidious instance from environment vars.
INVIDIOUS_INSTANCE=$(printenv INVIDIOUS_INSTANCE)
MPV_ARGUMENTS=$(printenv MPV_ARGUMENTS)

FINDER=$(printenv FINDER)

# If INVIDIOUS_INSTANCE is empty then make a default one.
if [ -z "$INVIDIOUS_INSTANCE" ]; then
	INVIDIOUS_INSTANCE="https://invidious.sevengames.xyz"
fi
if [ -z "$MPV_ARGUMENTS" ]; then
	MPV_ARGUMENTS="--no-terminal"
fi
if [ -z "$FINDER" ]; then
	FINDER="dmenu -l 30"
fi

# Prints the help screen then exits the program.
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
	printf "yt by 7Games (Benjamin) \
		\nusage: yt [-h, -i, -s [search]] \
		\n\n -i, --id\t gets the video by its video id \
		\n -s, --search\t takes in string and uses it to search with ytsearch \
		\n -h, --help\t displays this help and exit \
		\n\nMore info: man 1 yt\n"
	exit
fi

if [ "$1" = "-s" ] || [ "$1" = "--search" ]; then
	for thing in "$@"; do
		[ "${thing}" = "-s" ] || [ "${thing}" = "--search" ] && continue
		SEARCH_TERM=${SEARCH_TERM}${thing}" "
	done
elif [ "$1" = "-i" ] || [ "$1" = "--id" ]; then
	if [ -z "$2" ]; then
		exit
	fi

	mpv "$MPV_ARGUMENTS" "$INVIDIOUS_INSTANCE/watch?v=$2"

	exit
else
	# Gets input from FINDER and makes sures it's valid.
	case "$FINDER" in
		dmenu*) SEARCH_TERM=$(printf "" | dmenu -p "Search: ") ;;
		fzf*) printf "Search: " && read -r SEARCH_TERM ;;
		*) printf "Not a valid finder. Please use fzf or dmenu\n" && exit ;;
	esac
fi

# Gets all the results from ytsearch.
RESULTS="$(ytsearch "$SEARCH_TERM")"

# Prints out all the results and parses it to the FINDER, then gets the last -
# 12 characters then parses that to MPV with MPVs arguments and the Invidious -
# instance.
echo "$RESULTS" | xargs -I % -0 sh -c "printf \"%\" | $FINDER" | tail -c 12 | xargs -I % mpv "$MPV_ARGUMENTS" "$INVIDIOUS_INSTANCE/watch?v=%"

